Document: bytemark-client
Title: Debian bytemark-client Manual
Author: <insert document author here>
Abstract: This manual describes what bytemark-client is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/bytemark-client/bytemark-client.sgml.gz

Format: postscript
Files: /usr/share/doc/bytemark-client/bytemark-client.ps.gz

Format: text
Files: /usr/share/doc/bytemark-client/bytemark-client.text.gz

Format: HTML
Index: /usr/share/doc/bytemark-client/html/index.html
Files: /usr/share/doc/bytemark-client/html/*.html
