.\" t
.\"     Title: bytemark
.\"    Author: [see the "AUTHORS" section]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 12/29/2016
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "BYTEMARK" "1" "12/29/2016" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
bytemark \- command\-line client for managing services with Bytemark
.SH "SYNOPSIS"
.sp
\fBbytemark\fR [\fBglobal options\fR] \fIcommand\fR [\fBcommand options\fR] [\fBcommand arguments\fR]
.SH "DESCRIPTION"
.sp
\fBbytemark\fR is a command\-line client you can use to interact with Bytemark services (\fBhttps://www\&.bytemark\&.co\&.uk/\fR)\&.
.sp
You can use this software to signup for a new Bytemark account, or to use an existing account\&. You can perform a variety of tasks, such as create a Cloud Server, manage an existing Cloud Server, or connect to a Cloud Server via serial console\&. Get started straight away by running \fBbytemark help\fR\&.
.sp
If you\(cqre a programmer, you might also want to integrate with our API (\fBhttps://www\&.bytemark\&.co\&.uk/docs/api/\fR)\&.
.SH "GLOBAL OPTIONS"
.sp
Global options apply to any subsequent command\&.
.PP
\fB\-\-help\fR
.RS 4
Show usage instructions, including a list of available commands\&.
.RE
.PP
\fB\-\-help\fR \fIcommand\fR
.RS 4
Show instructions on how to use a specific command\&.
.RE
.PP
\fB\-\-yubikey\fR
.RS 4
Use this option if you have a Bytemark\-provided Yubikey that you use for authentication\&. You\(cqll be prompted for the one\-time password\&.
.RE
.PP
\fB\-\-yubikey\-otp\fR \fIstring\fR
.RS 4
Use this option if you want enter the Yubikey one\-time password on the command\-line rather than be prompted for it\&.
.RE
.PP
\fB\-\-debug\-level\fR \fInum\fR
.RS 4
Set the verbosity of debugging information (for troubleshooting purposes)\&.
.RE
.PP
\fB\-\-user\fR \fIusername\fR
.RS 4
Specify the username to use for the subsequent command\&. This is the same username you would use to login to the Bytemark Panel (\fBhttps://panel\&.bytemark\&.co\&.uk/\fR)\&.
.RE
.PP
\fB\-\-account\fR \fIaccount_name\fR
.RS 4
Specify the account to use for the subsequent command\&. Most people have a single account with the same name as their username, so don\(cqt need to use this option\&. However, some people manage Cloud Servers on multiple accounts\&.
.RE
.PP
\fB\-\-endpoint\fR \fIURL\fR, \fB\-\-billing\-endpoint\fR \fIURL\fR, \fB\-\-auth\-endpoint\fR \fIURL\fR
.RS 4
The default endpoints shouldn\(cqt need to be changed, but if for some reason you need the client to communicate with different endpoints then you can use these options\&.
.RE
.PP
\fB\-\-config\-dir\fR \fIdir\fR
.RS 4
The client stores its configuration in $HOME/\&.bytemark by default\&. You can specify a different directory with this option\&.
.RE
.SH "COMMANDS"
.sp
There are a variety of commands that let you easily manage your services with Bytemark\&. Get started by running \fBbytemark help\fR\&.
.PP
\fBhelp\fR
.RS 4
Show usage instructions, including a list of available commands\&.
.RE
.PP
\fBhelp command\fR
.RS 4
Show instructions on how to use a specific command\&.
.RE
.SH "EXAMPLES"
.PP
\fBbytemark help create\fR
.RS 4
Show instructions on how to use the
\fIcreate\fR
command\&.
.RE
.PP
\fBbytemark help create server\fR
.RS 4
Show instructions on how to use the
\fIcreate server\fR
command\&.
.RE
.PP
\fBbytemark create server \-\-authorized\-keys\-file ~/\&.ssh/id_rsa\&.pub stoneboat\&.http\fR
.RS 4
Creates a new Cloud Server called
\fIstoneboat\fR
in the
\fIhttp\fR
group\&. The specified public key will be installed to the root user so that you can use it to login\&.
.RE
.PP
\fBbytemark show server stoneboat\&.http\fR
.RS 4
Show information about the Cloud Server
\fIstoneboat\fR
in the
\fIhttp\fR
group\&.
.RE
.PP
\fBbytemark shutdown stoneboat\&.http\fR
.RS 4
Shutdown the Cloud Server
\fIstoneboat\fR
in the
\fIhttp\fR
group\&.
.RE
.SH "FILES"
.PP
\fI~/\&.bytemark\fR
.RS 4
Configuration is stored in this directory by default\&.
.RE
.PP
\fI~/\&.bytemark/debug\&.log\fR
.RS 4
This log holds debugging information\&. If you encounter a problem with this software, we might ask you to provide a copy of this file\&.
.RE
.PP
\fI~/\&.bytemark/token\fR
.RS 4
This is where the time\-limited authentication token is stored\&.
.RE
.SH "BUGS"
.sp
Please send an email to \fB<\fR\fBsupport@bytemark\&.co\&.uk\fR\fB>\fR if you encounter any problems and we\(cqll be more than happy to assist\&.
.SH "AUTHORS"
.sp
This software and associated documentation is developed and maintained by Bytemark, primarily by Telyn Z\&. Roat\&.
