// Code generated by "stringer -type Endpoint"; DO NOT EDIT.

package lib

import "strconv"

const _Endpoint_name = "AuthEndpointBrainEndpointBillingEndpointSPPEndpointAPIEndpoint"

var _Endpoint_index = [...]uint8{0, 12, 25, 40, 51, 62}

func (i Endpoint) String() string {
	if i < 0 || i >= Endpoint(len(_Endpoint_index)-1) {
		return "Endpoint(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Endpoint_name[_Endpoint_index[i]:_Endpoint_index[i+1]]
}
